spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TheDailyCircular?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false