spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TheDailyCircular?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: <emailaddress>
    password: <password>
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
